if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/synchronization/test_mutex_unify[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/synchronization/test_mutex_unify[1]_tests.cmake")
else()
  add_test(test_mutex_unify_NOT_BUILT test_mutex_unify_NOT_BUILT)
endif()
