if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/synchronization/test_task_semaphore[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/synchronization/test_task_semaphore[1]_tests.cmake")
else()
  add_test(test_task_semaphore_NOT_BUILT test_task_semaphore_NOT_BUILT)
endif()
