if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/stackless/test_coroutine_awaiters[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/stackless/test_coroutine_awaiters[1]_tests.cmake")
else()
  add_test(test_coroutine_awaiters_NOT_BUILT test_coroutine_awaiters_NOT_BUILT)
endif()
