if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/futures/test_cancelable_future[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/futures/test_cancelable_future[1]_tests.cmake")
else()
  add_test(test_cancelable_future_NOT_BUILT test_cancelable_future_NOT_BUILT)
endif()
