if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/futures/test_future_basic[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/futures/test_future_basic[1]_tests.cmake")
else()
  add_test(test_future_basic_NOT_BUILT test_future_basic_NOT_BUILT)
endif()
