if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/interrupt/test_task_cancellation[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/interrupt/test_task_cancellation[1]_tests.cmake")
else()
  add_test(test_task_cancellation_NOT_BUILT test_task_cancellation_NOT_BUILT)
endif()
