if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/scheduler/test_deadline_timer[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/scheduler/test_deadline_timer[1]_tests.cmake")
else()
  add_test(test_deadline_timer_NOT_BUILT test_deadline_timer_NOT_BUILT)
endif()
