if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/scheduler/test_scheduler_lifecycle[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/scheduler/test_scheduler_lifecycle[1]_tests.cmake")
else()
  add_test(test_scheduler_lifecycle_NOT_BUILT test_scheduler_lifecycle_NOT_BUILT)
endif()
