if(EXISTS "/home/runner/work/fast_task/fast_task/build_test/tests/threading/test_lock_guards[1]_tests.cmake")
  include("/home/runner/work/fast_task/fast_task/build_test/tests/threading/test_lock_guards[1]_tests.cmake")
else()
  add_test(test_lock_guards_NOT_BUILT test_lock_guards_NOT_BUILT)
endif()
