add_library(fast_task_flags INTERFACE)


target_compile_definitions(fast_task_flags INTERFACE ENABLE_BOOST_PREPROCESSOR ON)

if(FAST_TASK_ENABLE_DEBUG_API)
    target_compile_definitions(fast_task_flags INTERFACE FT_DEBUG_API_ENABLED)
endif()
if(FAST_TASK_INCLUDE_THREAD_INTERRUPT_CODE OR FAST_TASK_ENABLE_PREEMPTIVE_SCHEDULER)
    target_compile_definitions(fast_task_flags INTERFACE FT_INCLUDE_THREAD_INTERRUPT_CODE)
    if(WIN32)
        if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
            message(FATAL_ERROR 
                "fast_task: Thread interrupt and preemptive scheduling are currently only implemented "
                "in assembly for x86_64 in windows. Your target processor is: ${CMAKE_SYSTEM_PROCESSOR}. "
                "Please disable these features to compile on this architecture."
            )
        endif()
    endif()
endif()
if(FAST_TASK_ENABLE_ABORT_IF_ALREADY_STARTED)
    target_compile_definitions(fast_task_flags INTERFACE FT_ENABLE_ABORT_IF_ALREADY_STARTED)
endif()
if(FAST_TASK_ENABLE_ABORT_IF_NEVER_STARTED)
    target_compile_definitions(fast_task_flags INTERFACE FT_ENABLE_ABORT_IF_NEVER_STARTED)
endif()
if(FAST_TASK_ENABLE_PREEMPTIVE_SCHEDULER)
    target_compile_definitions(fast_task_flags INTERFACE FT_ENABLE_PREEMPTIVE_SCHEDULER)
endif()
if(FAST_TASK_EXCEPTION_POLICY STREQUAL "CHECK")
    target_compile_definitions(fast_task_flags INTERFACE FT_EXCEPTION_POLICY_CHECK)
elseif(FAST_TASK_EXCEPTION_POLICY STREQUAL "PRESERVE")
    target_compile_definitions(fast_task_flags INTERFACE FT_EXCEPTION_POLICY_PRESERVE)
endif()
target_compile_definitions(fast_task_flags INTERFACE FT_TASK_TRANSFERS_LIMIT=${FAST_TASK_TASK_TRANSFERS_LIMIT})
target_compile_definitions(fast_task_flags INTERFACE FT_GUARD_PAGE_COUNT=${FAST_TASK_GUARD_PAGE_COUNT})

if(FAST_TASK_TIMER_PRECISION STREQUAL "1us")
    target_compile_definitions(fast_task_flags INTERFACE FT_TIMER_PRECISION=1)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_compile_definitions(fast_task_flags INTERFACE FT_HAS_HIRES_TIMER)
    elseif(WIN32)
        target_compile_definitions(fast_task_flags INTERFACE FT_HAS_HIRES_TIMER)
    elseif(APPLE)
        target_compile_definitions(fast_task_flags INTERFACE FT_HAS_HIRES_TIMER)
    endif()
elseif(FAST_TASK_TIMER_PRECISION STREQUAL "10ms")
    target_compile_definitions(fast_task_flags INTERFACE FT_TIMER_PRECISION=10000)
else()
    target_compile_definitions(fast_task_flags INTERFACE FT_TIMER_PRECISION=1000)
endif()

if(FAST_TASK_MAX_EXECUTORS)
    target_compile_definitions(fast_task_flags INTERFACE FT_MAX_EXECUTORS=${FAST_TASK_MAX_EXECUTORS})
endif()
if(FAST_TASK_BINDED_MAX_SLOTS)
    target_compile_definitions(fast_task_flags INTERFACE FT_BINDED_MAX_SLOTS=${FAST_TASK_BINDED_MAX_SLOTS})
endif()
if(FAST_TASK_MAX_STEAL_ATTEMPTS)
    target_compile_definitions(fast_task_flags INTERFACE FT_MAX_STEAL_ATTEMPTS=${FAST_TASK_MAX_STEAL_ATTEMPTS})
endif()

if(MSVC)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/utf-8>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/wd4505>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/wd4324>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/wd4717>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/sdl>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/GF>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/W4>)
    if(FAST_TASK_WARNINGS_AS_ERRORS)
        target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/WX>)
    endif()
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/MP>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/Zc:preprocessor>)
    target_compile_options(fast_task_flags INTERFACE $<$<COMPILE_LANGUAGE:CXX>:/permissive->)
else()
    if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebugInfo")
        target_compile_options(fast_task_flags INTERFACE -flto)
    endif()
    target_compile_options(fast_task_flags INTERFACE -Wall -Wextra --pedantic)
    target_compile_options(fast_task_flags INTERFACE -Wno-interference-size)
    target_compile_options(fast_task_flags INTERFACE -Wno-cast-function-type)
endif()

if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    target_compile_options(fast_task_flags INTERFACE -Wno-unused-function)
    
    if(MSVC)
        target_compile_options(fast_task_flags INTERFACE /clang:-ftemplate-backtrace-limit=0)
    endif(MSVC)
endif()
